In [4]:
import jax.numpy as jnp
theta_dis = 2000

theta_index = theta_dis * (jnp.pi/ 2.) / (2. * jnp.pi)
theta_index = jnp.fmod(theta_index, theta_dis)
print(theta_index)

500.0


In [10]:
import jax.numpy as jnp
theta_dis = 1800
theta_index_increment = 1000/1799
theta_index2 = jnp.arange(0, jnp.pi, theta_index_increment)
print(theta_index2)

[0.        0.5558644 1.1117288 1.6675932 2.2234576 2.779322 ]


In [9]:
import numpy as np 
theta_dis = 1800
theta_index_increment = np.pi / theta_dis
num_beams = 1800
for i in range(1, num_beams):
    # increment the beam index
    theta_index2[i] = theta_index2[i - 1] + theta_index_increment
print(theta_index2)


TypeError: '<class 'jaxlib.xla_extension.ArrayImpl'>' object does not support item assignment. JAX arrays are immutable. Instead of ``x[idx] = y``, use ``x = x.at[idx].set(y)`` or another .at[] method: https://jax.readthedocs.io/en/latest/_autosummary/jax.numpy.ndarray.at.html

In [7]:
from jax import lax 
theta_index = -198
theta_dis = 2000

def cond_fun(theta_index):
    return theta_index < 0
def body_fun(theta_index):
    return theta_index + theta_dis
theta_index = lax.while_loop(cond_fun, body_fun, theta_index)
print(theta_index)


1802


In [13]:
import jax.numpy as jnp 

arr_empty = jnp.empty((2, 3))
arr_zeros = jnp.zeros((2, 3))
print(arr_empty)
print(arr_zeros)

[[0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 0.]
 [0. 0. 0.]]


In [29]:
import jax.numpy as jnp 
import numpy as np 

theta_index_ = 800
theta_index_increment = 1.3865
num_beams = 1080
theta_dis = 2000
theta_index2_old = np.zeros((num_beams,))
theta_index2_old[0] = theta_index_
for i in range(1, num_beams):
    # increment the beam index
    theta_index2_old[i] = theta_index2_old[i - 1] + theta_index_increment

theta_index2_new = jnp.arange(theta_index_, theta_index_+(num_beams * theta_index_increment), theta_index_increment)

theta_index_arr_clipped = jnp.minimum(theta_index2_new, theta_dis)
print(len(theta_index2_old))
print(len(theta_index2_new))
print(len(theta_index_arr_clipped))
print(theta_index_arr_clipped)

1080
1080
1080
[ 800.       801.3865   802.77295 ... 2000.      2000.      2000.     ]


In [4]:
import numpy as np 
from jax import random 

random = random.PRNGKey(1)
random_numpy = np.random.default_rng(seed=1)
print(random)
print(random_numpy)

[0 1]
Generator(PCG64)


In [4]:
import numpy as np 
from jax import random 
import jax.numpy as jnp 

std_dev = 0.01
num_beams = 1080

numpy_rng = np.random.default_rng(seed=1)
jax_rng = random.PRNGKey(seed=1)

noise_jax = random.normal(jax_rng, (num_beams,), dtype=jnp.float32) * std_dev
noise_numpy = numpy_rng.normal(0., std_dev, num_beams)

print(noise_jax)
print(noise_numpy)

[ 0.00266566  0.01134311 -0.00160945 ... -0.01251915  0.00264459
 -0.00865252]
[ 0.00345584  0.00821618  0.00330437 ... -0.0050708   0.01580457
  0.00178266]


In [ ]:
import jax
import jax.numpy as jnp

# Assuming vertices is your input array
vertices = jnp.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Define the rolling function
def roll_fn(shift):
    return jnp.roll(vertices, shift, axis=0)

# Define the shift values from 0 to vertices.shape[0] - 1
shift_values = jnp.arange(vertices.shape[0])

# Use jax.vmap to apply the roll function to all shift values
shifted_arrays = jax.vmap(roll_fn)(shift_values)

# shifted_arrays is now a collection of arrays, each corresponding to a shifted version of vertices
# shifted_arrays[0] corresponds to the original vertices, and shifted_arrays[i] corresponds to the vertices shifted by i positions

print(shifted_arrays)